server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('product.urls')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
    path('tinymce', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Free adverts Administrative site"
admin.site.site_title = "Freeadverts Admin Portal"
admin.site.index_title = "Welcome to Free advert's Administrative Portal"

users/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login', views.login, name='login'),    
    path('register', views.register, name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from users.models import User
from bootstrap_modal_forms.forms import BSModalModelForm
from django.contrib.auth.forms import AuthenticationForm



class Registrationform(BSModalModelForm,UserCreationForm):


    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2', 'phone']
        error_messages = {
            'first_name': {
                'required': 'First name is required',
                'max_length': 'Name is too long'
            },
            'last_name': {
                'required': 'Last name is required',
                'max_length': 'Last Name is too long'
            },
            'username': {
                'required': 'Username is required',
                 'max_length': 'Last Name is too long',
                 'unique': "A user with that username already exists.",
            }
        }




class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password'})

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)

            if self.user is None:
                raise forms.ValidationError("User Does Not Exist.")
            if not self.user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not self.user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)

    def get_user(self):
        return self.user

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissable">
   <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
   <strong>{{ field.name }} {{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% endif %}
<div class="page-content pt-150 pb-150">
   <div class="container">
      <div class="row">
         <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
            <div class="row">
               <div class="col-lg-6 pr-30 d-none d-lg-block">
                  <img class="border-radius-15" src="{% static '/imgs/page/login-1.png' %}" alt="">
               </div>
               <div class="col-lg-6 col-md-8">
                  <div class="login_wrap widget-taber-content background-white">
                     <div class="padding_eight_all bg-white">
                        <div class="heading_s1">
                           <h1 class="mb-5">Login</h1>
                           <p class="mb-30">Don't have an account? <a href="{% url 'users:register' %}">Create here</a>
                           </p>
                        </div>
                        <form action="{% url 'users:login' %}" method="POST">
                           {% csrf_token %}
                           <div class="form-group">
                              <input type="tel" required="" name="username" placeholder="Phone Number *">
                           </div>
                           <div class="form-group">
                              <input required="" type="password" name="password" placeholder="Your password *">
                           </div>
                           <div class="login_footer form-group">
                              <div class="chek-form">
                                 <input type="text" required="" name="email" placeholder="Security code *">
                              </div>
                              <span class="security-code">
                                 <b class="text-new">8</b>
                                 <b class="text-hot">6</b>
                                 <b class="text-sale">7</b>
                                 <b class="text-best">5</b>
                              </span>
                           </div>
                           <div class="login_footer form-group mb-50">
                              <div class="chek-form">
                                 <div class="custome-checkbox">
                                    <input class="form-check-input" type="checkbox" name="checkbox"
                                       id="exampleCheckbox1" value="">
                                    <label class="form-check-label" for="exampleCheckbox1"><span>Remember
                                          me</span></label>
                                 </div>
                              </div>
                              <a class="text-muted" href="{% url 'users:password_reset' %}">Forgot password?</a>
                           </div>
                           <div class="form-group">
                              <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log
                                 in</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users-register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }}Free Adverts Kenya account
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="page-content pt-150 pb-150">
   <div class="container">
      <div class="row">
         <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
            <div class="row">
               <div class="col-lg-6 col-md-8">
                  <div class="login_wrap widget-taber-content background-white">
                     <div class="padding_eight_all bg-white">
                        <div class="heading_s1">
                           <h1 class="mb-5">Create an Account</h1>
                           <p class="mb-30">Already have an account? <a href="page-login.html">Login</a></p>
                        </div>
                        <form action="{% url 'users:register' %}" method="POST">
                           {% csrf_token %}
                           <div class="form-group">
                              <input type="text" required="" name="first_name" placeholder="first Name">
                           </div>
                           <div class="form-group">
                              <input type="tel" required="" name="phone" placeholder="Phone Number">
                           </div>
                           <div class="form-group">
                              <input type="email" required="" name="email" placeholder="Email">
                           </div>
                           <div class="form-group">
                              <input required="" type="password" name="password" placeholder="Password">
                           </div>
                           <div class="form-group">
                              <input required="" type="password" name="password2" placeholder="Confirm password">
                           </div>
                           <div class="form-group">
                              <input type="text" name="referral_code" class="form-control" placeholder="Referral Code">
                           </div>
                           <div class="login_footer form-group">
                              <div class="chek-form">
                                 <input type="text" required="" name="email" placeholder="Security code *">
                              </div>
                              <span class="security-code">
                                 <b class="text-new">8</b>
                                 <b class="text-hot">6</b>
                                 <b class="text-sale">7</b>
                                 <b class="text-best">5</b>
                              </span>
                           </div>
                           <div class="login_footer form-group mb-50">
                              <div class="chek-form">
                                 <div class="custome-checkbox">
                                    <input class="form-check-input" type="checkbox" name="checkbox"
                                       id="exampleCheckbox12" value="">
                                    <label class="form-check-label" for="exampleCheckbox12"><span>I
                                          agree to terms &amp; Policy.</span></label>
                                 </div>
                              </div>
                              <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean
                                 more</a>
                           </div>
                           <div class="form-group mb-30">
                              <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold"
                                 name="login">Submit &amp; Register</button>
                           </div>
                           <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will
                              be used to support your experience throughout this website, to manage
                              access to your account, and for other purposes described in our privacy
                              policy</p>
                        </form>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6 pr-30 d-none d-lg-block">
                  <div class="card-login mt-115">
                     <a href="#" class="social-login facebook-login">
                        <img src="{% static '/imgs/theme/icons/logo-facebook.svg' %}" alt="">
                        <span>Continue with Facebook</span>
                     </a>
                     <a href="#" class="social-login google-login">
                        <img src="{% static '/imgs/theme/icons/logo-google.svg' %}" alt="">
                        <span>Continue with Google</span>
                     </a>
                     <a href="#" class="social-login apple-login">
                        <img src="{% static 'imgs/theme/icons/logo-apple.svg' %}" alt="">
                        <span>Continue with Apple</span>
                     </a>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}