product/urls.py
from django.conf.urls import url
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


from .views import CreateBoostedItems, CreateProductView2, DetailProductView, DraftsListView, EditProductView, Jobapplicationview, MyActiveProductsListView, MyClosedProductsListView, MyDraftProductsListView, MyProductsListView, ProductListView, CreateProductView, close_product, delete_product, post_image, delete_image, publish_product, ProductList1
from .home import *
app_name = "products"
urlpatterns = [
    path("", home_view, name="home"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("", ProductListView.as_view(), name="list"),
    path("new-product/", CreateProductView.as_view(), name="create_new"),
    path("new-product/", CreateProductView2.as_view(), name="createview2"),
    path("boost-item/", CreateBoostedItems.as_view(), name="boost-item"),
    path("job/", Jobapplicationview.as_view(), name="Job"),
    path("post-image/", post_image, name="post_image"),
    path("delete-image/", delete_image, name="delete_image"),
    path("delete/(?<id>\d+)/", delete_product, name="delete_property"),
    path("close/(?<id>\d+)/", close_product, name="close_property"),
    path("publish/(?<id>\d+)/", publish_product, name="publish_property"),
    path("my_listings/", MyProductsListView.as_view(), name="my_listings"),
    path("my_active_listings/", MyActiveProductsListView.as_view(), name="my_active_listings"),
    path("my_draft_listings/", MyDraftProductsListView.as_view(), name="my_draft_listings"),
    path("my_closed_listings/", MyClosedProductsListView.as_view(), name="my_closed_listings"),
    path("my-drafts/", DraftsListView.as_view(), name="drafts"),
    path("edit/(?<pk>\d+)/", EditProductView.as_view(), name="edit_product"),
    path("(?<slug>[-\w]+)/", DetailProductView.as_view(), name="listing"),


    path('', home_view, name="list"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path('products', ProductListView.as_view(), name="list"),
    # path('new-product/', CreateProductView.as_view(), name="create_new"),
    path('post-image/', post_image, name="post_image" ),
    path('boost-item/', CreateBoostedItems.as_view(), name="boost_item"),
    path('delete-image/', delete_image, name = "delete_image"),
    path('delete/(?<id>\d+', delete_product, name="delete_property"),
    path('close/(?<id>\d+)/',close_product, name="close_property"),
    path('publish/(?<id>\d+)/', publish_product, name="publish_product"),
    path('my_listings/', MyProductsListView, name="my_listings"),
    path('my_active_listings/', MyActiveProductsListView, name="my_active_listings"),
    path('my_draft_listings/', MyDraftProductsListView, name="my_draft_listings"),
    path('my_closed_listings/', MyClosedProductsListView, name= "my_closed_listings"),
    path('my-drafts/', DraftsListView, name="drafts"),
    path('edit/(?<pk>\d+)/', EditProductView, name="edit_product"),
    path('(?<slug>[-\w]+)/', DetailProductView, name="Product"),
    path('category/<category_slug>/', ProductList1.as_view(), name = "product_list_by_category")
]+ static(settings.STATIC_URL, document_root=settings.STATIC_URL)

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('product.urls')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
    path('tinymce', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Free adverts Administrative site"
admin.site.site_title = "Freeadverts Admin Portal"
admin.site.index_title = "Welcome to Free advert's Administrative Portal"

users/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login', views.login, name='login'),    
    path('register', views.register, name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

product/forms.py
from django import forms
from django.db.models import fields
from django.forms.fields import ImageField

from markdownx.fields import MarkdownxFormField
from multiupload.fields import MultiImageField

from .models import BoostedItem, Brand, Jobapplication, Subcategory, area, product, image, Model


class Productform(forms.ModelForm):
    image = forms.ImageField()
    class Meta:
        model = product
        fields = ["title", "Description", "category", "Subcategory", "Brand", "Model", "county", "location","price", "image", "image2", "image3"]


class Productform2(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(Productform2, self).__init__(*args, **kwargs)
        self.fields['category'].label = "category"
        self.fields['Subcategory'].label = "Subcategory"
        self.fields['Brand'].label = "Brand"
        self.fields['Model'].label = "Model"
        self.fields['county'].label = "County"
        self.fields['location'].label = "location"
        self.fields['image'].label = " Product Image"
        self.fields['image2'].label = "Product image"
        self.fields['image3'].label = "Product Image"


    class Meta:
        model = product
        fields = ["category", "Subcategory", "Brand", "Model", "county", "location", "image", "image2", "image3"]

    def is_valid(self):
        valid = super(Productform2, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        Product = super(Productform2, self).save(commit=False)
        
        if commit:
            return Product.save()
        return Product


class Boostedform(forms.ModelForm):
    def __init__(self, user,*args, **kwargs):
        super(Boostedform,self).__init__(*args, **kwargs)
        self.fields['product'].queryset = product.objects.filter(user=user)

    class Meta:
        model = BoostedItem
        fields = ["product", "type"]


class Jobform(forms.ModelForm):
    class Meta:
        model=Jobapplication
        fields=['name', 'jobgroup', 'CV']

product/views.py
from django.db.models.fields import EmailField
from product.models import product
from django.shortcuts import redirect, render, get_object_or_404
from .models import BoostedItem, Jobapplication, Subcategory, product, image, Category
import operator
import functools
import logging
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
import json
from django.contrib import messages
from django.urls import reverse
from .helpers import AuthorRequiredMixin, ajax_required
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse,Http404
from .forms import Jobform, Productform , Productform2, Boostedform
from django.db.models import Q
from mpesa_api.core.mpesa import Mpesa
from django.utils import timezone
from sweetify.views import SweetifySuccessMixin
from django.urls import reverse_lazy


# Create your views here.


class ProductListView(ListView):
    """Basic ListView implementation to call the published articles list."""

    model = product
    paginate_by = 16
    context_object_name = "products"
    template_name = "product/products.html"

    def get_queryset(self):
        return self.model.objects.all().order_by('-timestamp')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trendings"] = self.model.objects.filter(timestamp__month=timezone.now().month)[:3]
        return context

class ProductList1(ListView):
    template_name = 'product_list.html'
    model = product
    paginate_by = 8
    context_object_name = 'products'

    def get_queryset(self, **kwargs):
        self.category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        products=product.objects.filter(category=self.category.id)
        return product.objects.filter(category=self.category).order_by('-timestamp')

    def get_context_data(self, **kwargs):
        context = super(ProductList1, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context


class MyProductsListView(ListView):
    """Basic ListView implementation to call the published articles list."""

    model = product
    paginate_by = 20
    context_object_name = "products"
    template_name = "product/my-products.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = "My Listings"
        return context

    def get_queryset(self, **kwargs):
        return product.objects.filter(user=self.request.user).order_by('-timestamp')

class CreateBoostedItems(LoginRequiredMixin, CreateView):
    model= BoostedItem
    message = 'You have succesfully Boosted your product'
    form_class= Boostedform
    template_name='product/productBoost.html'



    def get_queryset(self, **kwargs):
        return product.objects.filter(user=self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user

        phone = self.request.user.phone
        price = form.instance.price
        # Mpesa credantials required
        # To-Do
        # Mpesa.c2b_register_url()
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("products:my_listings")


class MyActiveProductsListView(MyProductsListView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = "My Active Listings"
        return context

    def get_queryset(self, **kwargs):
        return product.objects.filter(user=self.request.user, status='OPEN').prefetch_related(Prefetch("images", queryset=image.objects.order_by("index"), to_attr="image"))


class MyDraftProductsListView(MyProductsListView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = "My Draft Listings"
        return context

    def get_queryset(self, **kwargs):
        return product.objects.filter(user=self.request.user, status='DRAFT').prefetch_related(Prefetch("images", queryset=image.objects.order_by("index"), to_attr="image"))

class MyClosedProductsListView(MyProductsListView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = "My Closed Listings"
        return context

    def get_queryset(self, **kwargs):
        return product.objects.filter(user=self.request.user, status='CLOSED').prefetch_related(Prefetch("images", queryset=image.objects.order_by("index"), to_attr="image"))


class DraftsListView(MyProductsListView):
    """Overriding the original implementation to call the drafts articles
    list."""

    def get_queryset(self, **kwargs):
        return product.objects.get_drafts()

class CreateProductView(LoginRequiredMixin,CreateView,SweetifySuccessMixin):

    model = product
    message = "Your product has been created."
    form_class = Productform
    template_name = "product/product_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user


        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("products:list")




class CreateProductView2(LoginRequiredMixin,CreateView,SweetifySuccessMixin):

    model=product
    form_class= Productform2
    template_name = 'product/product_create2.html'


    def get_object(self, queryset=None):
        return self.model.objects.get(id = self.request.session['form_data'])


    def post(self, request, *args, **kwargs):
        form = self.form_class(data = request.POST)
        if form.is_valid():
            Product = self.model.objects.get(id = request.session['product'])
            Product.Subcategory = request.POST.get('Subcategory')
            Product.Brand= request.POST.get('Brand')
            Product.Model= request.POST.get('Model')
            Product.county= request.POST.get('county')
            Product.location= request.POST.get('location')
            Product.save()
            return redirect('products:list')

        else:
            return render(request, "product/product_create2.html", {form:form})



    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("products:list")





class Jobapplicationview(LoginRequiredMixin, CreateView):
    model=Jobapplication
    message = "You have successfully posted your CV"
    form_class=Jobform
    template_name='Jobs/Jobs.html'
    def form_valid(self, form):
        form.instance.user = self.request.user


        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("products:home")




class EditProductView(AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""

    model = product
    message = "Your product has been updated."
    form_class = Productform
    template_name = "product/product_edit.html"    
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['image'] = image.objects.filter(listing=self.object)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        listing = form.save(commit=True)
        images = form.cleaned_data['image']
        image_ids = json.loads(images)
        index = 0

        for im_id in image_ids:
            image = image.objects.get(id=im_id)
            image.listing = listing
            image.index = index
            image.save()
            index += 1

        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("products:my_listings")

class DetailProductView(DetailView):
    """Basic DetailView implementation to call an individual product."""

    model = product

    def get_object(self):
        obj = super(DetailProductView, self).get_object()
        obj.views+=1
        obj.save
        if obj is None:
            raise Http404("Product does not exist")
        return obj


        

@login_required
@ajax_required
@require_http_methods(["POST"])
def post_image(request):
    """A function view to implement the post functionality with AJAX allowing
    to create News instances as parent ones."""

    image = request.FILES["image"]
    if image is not None:
        image = image.objects.create(image=image)

        return JsonResponse({"id": image.id})

    else:
        return HttpResponseBadRequest(
            content=_(f"No Image uploaded.")
        )

@login_required
@ajax_required
@require_http_methods(["POST"])
def delete_image(request):
    """A function view to implement the post functionality with AJAX allowing
    to create News instances as parent ones."""

    image = request.POST["image"]
    if image is not None:
        image = image.objects.filter(id=image).delete()

        return JsonResponse({"id": image})

    else:
        return HttpResponseBadRequest(
            content=_(f"No Image Id provided.")
        )

@login_required
@ajax_required
@require_http_methods(["DELETE"])
def delete_product(request, id):

    product = product.objects.filter(id=id, user=request.user).first()

    if product is not None:
        product.delete()
        return JsonResponse({"status": 200})

    else:
        return JsonResponse({"status": 403, "error": "Listing could not be found"})

templates/product/my-products.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="breadcrumb-bar">
              <div class="page-breadcrumb-list">
                <ul>
                  <li class="breadcrumb-nav">
                    <a href="index.html">Your products</a>
                  </li>
                  <li class="breadcrumb-nav sub-title">( {{ products.count }} products)</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="container">
          <div class="row mb-4">
            <div class="col-lg-6">
            {% if products.count < 1 %}
              <div class="page-title">
                <h2>You Have No Products</h2>
              </div>
            {% endif %}
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="filters-section form-style-1">
                <div class="filter-card">
                  <h5 class="mb-3">All Categories</h5>
                  <ul class="category-list">
                  {% show_categories_side %}
                  </ul>
                </div>

              </div>
            </div>
            <div class="col-lg-9">
              <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 col-6 d-flex flex-wrap">
                  <div class="products-card flex-fill">
                    <div class="products-img">
                      <a href="{% url 'products:listing' product.slug %}">
                        <img src="{{ product.image.url }}" alt="" style="width: 300px;height: 200px;">
                      </a>
                    </div>
                    <div class="products-body">
                      <h4 class="products-title text-truncate">
                        <a href="{% url 'products:listing' product.slug %}">{{ product.title }}</a>
                      </h4>
                      <p class="product-info">
                      <a href="{{ product.category.get_absolute_url }}" class="product-catagory">{{ product.category }}</a>
                      </p>
                      <ul class="ratings pb-2">
                        <li class="ratings-count">Number of views({{ product.views }}) </li>
                      </ul>
                      <h5 class="products-price">KSH {{product.price}}</h5>
                      <p class="products-price-offer">
                        {{product.county}}
                      </p>
                      <a href="{% url 'products:listing' product.slug %}" class="prd-btn">More Details</a>
                    </div>
                  </div>
                </div>
                {% endfor %}

                {% if page_obj.paginator.num_pages > 1 %}

                        {% include '_pagination.html' with page_obj=page_obj %}

                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/product/productBoost.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}




{% block content %}
      <div class="page-content">
        <div class="container">
          <div class="row">
{% block menu %}
            <div class="col-md-3">
              <div class="profile-menu">
                <ul class="profile-links">
                  <li>
                    <a href="#" class="active">Boost Your Items</a>
                  </li>
                </ul>
              </div>
            </div>

{% endblock menu %}
            <div class="col-md-9">
              <div class="tab-content">
                <div class="tab-pane show active" id="account">
                  <h4 class="mb-3">Boost Your Items</h4>
                  <div class="row">
                    <div class="col-md-12">

                        <div id="pricing-table" class="clear">
                            <div class="plan">
                                <h3>Regular<span>Free</span></h3>
                                <a class="btn btn-primary btn-block pass-btn">One month</a>        
                                <ul>
                                    <li><b>No</b> Boosted Items</li>			
                                </ul> 
                            </div>
                            <div class="plan" id="most-popular">
                                <h3>Premium<span>599</span></h3>
                                <a class="btn btn-primary btn-block pass-btn">One month</a>        
                                <ul>
                                    <li><b>#1</b> Show in Special category</li>
                                    <li><b>#2</b> Ads run twice a day</li>			
                                </ul>    
                            </div>
                            <div class="plan">
                                <h3>Platinum<span>1000</span></h3>
                                <a class="btn btn-primary btn-block pass-btn">One month</a>        
                                <ul>
                                    <li><b>#1</b> Show in Special category, at the top</li>
                                    <li><b>#2</b> Ads run Four times a day</li>				
                                </ul>
                            </div> 	
                        </div>

                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger alert-dismissable">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        <strong>{{ field.name }} {{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                        <form method="POST" action="{% url 'products:boost-item' %} ">
                        {% csrf_token %}
                        <div class="card-box card flex-fill">
                            <div class="clearfix"></div>
                                <div class="card-header">Product</div>
                                    <div class="card-body">
                                        <div class="form-row">
                                            <div class="col-lg-4 col-md-6">
                                                <div class="form-group">
                                                    <label>Product Name</label>
                                                    {{ form.product|add_class:"form-control" }}
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-6">
                                                <div class="form-group">
                                                    <label>Boost Type</label>
                                                    {{ form.type|add_class:"form-control" }}
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-6">
                                                <button type="submit" value='Submit' class="btn btn-primary btn-block pass-btn">Submit</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



{% endblock content %}

templates/product/product_create2.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
      <div class="page-content">
        <div class="container">
          <div class="row">
{% block menu %}
            <div class="col-md-3">
              <div class="profile-menu">
                <ul class="profile-links">
                  <li>
                    <a href="#" class="active">Create product</a>
                  </li>
                </ul>
              </div>
            </div>

{% endblock menu %}
            <div class="col-md-9">
              <div class="tab-content">
                <div class="tab-pane show active" id="account">
                  <h4 class="mb-3">Create Product</h4>
                  <div class="row">
                   {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ field.name }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    <div class="col-md-12">
                        <form enctype="multipart/form-data" class="form-horizontal" method="POST" action="{% url 'products:create_new' %} ">
                        {% csrf_token %}
                            <div class="card-box card flex-fill">
                            <div class="clearfix"></div>
                                <div class="card-header">Product Create Page</div>
                                <div class="card-body">
                                      <div class="form-row">

                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product category</label>
                                                {{ form.category|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Sub Category</label>
                                                {{ form.Subcategory|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Brand</label>
                                                {{ form.Brand|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Make</label>
                                                {{ form.Model|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product County location</label>
                                                {{ form.county|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product County location</label>
                                                {{ form.location|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Image 1</label>
                                                {{ form.image|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Image 2</label>
                                                {{ form.image2|add_class:"form-control" }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>Product Image 3</label>
                                                {{ form.image3|add_class:"form-control" }}
                                            </div>
                                        </div>
                                         </br>   
                                        <div class="col-lg-4 col-md-6"style="padding-top: 30px;">
                                            <button type="submit" class="btn btn-primary btn-block pass-btn">Next</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



{% endblock content %}

templates/product/product_edit.html
{% extends 'base.html' %}